# Предложения
## Получить список предложений

GET http://localhost:4500/offers HTTP/1.1
Content-Type: application/json

###

## Добавиьть новое предложение

POST http://localhost:4500/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Это лучшее превзащлкмьfgjyjyкзщшмокьк кщмкшмькм кщмьк",
  "description": "dpfsoerjfrpeojytjfyjvepvjrpv",
  "date": "2023-06-17T14:18:36.283Z",
  "city": "Paris",
  "previewImage": "e;lcekd.jmg",
  "images": ["page49.jpg", "page45.jpg", "page78.jpg", "page12.jpg", "page09.jpg", "page07.jpg"],
  "isPremium": false,
  "rating": 3,
  "type": "apartment",
  "bedrooms": 3,
  "maxAdults": 4,
  "price": 900,
  "goods": ["Breakfast", "Air conditioning", "Washer", "Towels"],
  "userId": "647b9c45bb1cfc74c5ea72de",
  "location": {
    "latitude": 5456,
    "longitude": 5465
    }
}
