# Предложения
## Получить список предложений

GET http://localhost:4500/offers?limit=60 HTTP/1.1
Content-Type: application/json

###

## Информация о предложении по идентификатору

GET http://localhost:4500/offers/647e2c6b576583b562b45a98 HTTP/1.1

###

##Получить список комментариев предложения

GET  http://localhost:4500/offers/647e2c6b576583b562b45a98/comments HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение

POST http://localhost:4500/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Это лучшее превзащлкмьfgjyjyкзщшмокьк кщмкшмькм кщмьк",
  "description": "dpfsoerjfrpeojytjfyjvepvjrpv",
  "date": "2023-06-17T14:18:36.283Z",
  "city": "Paris",
  "previewImage": "e;lcekd.jmg",
  "images": ["62823cb2c5a64ce9f1b50eba"],
  "isPremium": false,
  "rating": 3,
  "type": "apartment",
  "bedrooms": 3,
  "maxAdults": 4,
  "price": 900,
  "goods": ["62823cb2c5a63ce9f1b50eba"],
  "userId": "647b9c45bb1cfc74c5ea72de",
  "location": {
    "latitude": 5456,
    "longitude": 5465
    }
}

###

## Редактирование предложения

PATCH  http://localhost:4500/offers/647e327b6c1c7c0a0fe89e8c HTTP/1.1
Content-Type: application/json

{
  "type": "house",
  "bedrooms": 5,
  "maxAdults": 8,
  "price": 1100
}

###

## Удаление предложения

DELETE  http://localhost:4500/offers/647e2c6b576583b562b45a95 HTTP/1.1
Content-Type: application/json

###
